name: Build & Lint

on:
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-20.04
    name: 📦 Build Docker Image
    steps:
      - uses: actions/checkout@v2
      - name: Build Deploy Package
        run: docker build .